# Generated by Django 3.1.4 on 2021-01-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201227_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
