# Generated by Django 3.1.4 on 2020-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='horario_func',
            field=models.CharField(max_length=200),
        ),
    ]
